# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f4de2f694dcbfcd087cf65afdf42d7a65754c8d74a872bababe9c170f14ec892ff3e21903d1a4335346d991cfb0410a4b4013581b98011ba76e8cd36ad11972

test:
  secret_key_base: 6ad75525929352ac488de8589f7f69f2212695b9fa2ca3c53decdb1e3b579de74b9283cea376f19a46392c8c6123a91ade9c462abaca260cea01fe520a881171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
